name: sellerapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  velocity_x: ^4.1.2
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.5.2
  firebase_messaging: ^14.7.5
  flutter_local_notifications: ^16.2.0
  firebase_core: ^2.23.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/


  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf

