// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPc3iB7bgXnv8vnbCdTbLNHaQNP9FVN6U',
    appId: '1:864796309130:web:49e956814590db7fbbdf73',
    messagingSenderId: '864796309130',
    projectId: 'seller-app-872a6',
    authDomain: 'seller-app-872a6.firebaseapp.com',
    storageBucket: 'seller-app-872a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgeB3sCzk-boMIcl3IJWgUMNBxVsh9qVk',
    appId: '1:864796309130:android:a18e4814bf960b70bbdf73',
    messagingSenderId: '864796309130',
    projectId: 'seller-app-872a6',
    storageBucket: 'seller-app-872a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBR-LE-QQAvpURFXASSlHyD465K3ZVgk',
    appId: '1:864796309130:ios:82edbb983c867888bbdf73',
    messagingSenderId: '864796309130',
    projectId: 'seller-app-872a6',
    storageBucket: 'seller-app-872a6.appspot.com',
    iosBundleId: 'com.example.sellerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqBR-LE-QQAvpURFXASSlHyD465K3ZVgk',
    appId: '1:864796309130:ios:e64aa5925908e5f1bbdf73',
    messagingSenderId: '864796309130',
    projectId: 'seller-app-872a6',
    storageBucket: 'seller-app-872a6.appspot.com',
    iosBundleId: 'com.example.sellerapp.RunnerTests',
  );
}
